controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_redirect_root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_summary_index
        permanent: true
